# mysql 

development:
  adapter: mysql2
  encoding: utf8
  database: internos_prueba_dev
  pool: 5
  username: root
  password: 123

production:
  adapter: mysql2
  encoding: utf8
  database: internos_dev
  pool: 5
  username: internos
  password: uniINTERNOSadmin

test:
  adapter: mysql2
  encoding: utf8
  database: internos_prueba_test
  pool: 5
  username: root
  password: 123
